export type ToolCategory = 'text' | 'developer' | 'security' | 'converters' | 'seo' | 'utility'
export type ColorKey = 'purple' | 'teal' | 'coral' | 'pink' | 'amber' | 'emerald'

export interface Tool {
  id: string
  name: string
  category: ToolCategory
  color: ColorKey
  icon: string
  shortDesc: string
  longDesc: string
  keywords: string[]
  relatedTools: string[]
  faqs: { q: string; a: string }[]
}

export const TOOLS: Tool[] = [
  // ── TEXT TOOLS ─────────────────────────────────────────────
  {
    id: 'word-counter',
    name: 'Word Counter',
    category: 'text',
    color: 'teal',
    icon: '📝',
    shortDesc: 'Count words, characters, sentences, and paragraphs instantly.',
    longDesc: 'Free word counter tool that instantly counts words, characters (with and without spaces), sentences, paragraphs, lines, and estimates reading time. Perfect for writers, bloggers, students, and SEO professionals who need to meet specific content length requirements.',
    keywords: ['word counter', 'character counter', 'word count tool', 'text counter', 'count words online'],
    relatedTools: ['text-case-converter', 'word-frequency-counter', 'keyword-density-checker'],
    faqs: [
      { q: 'How accurate is the word counter?', a: 'Extremely accurate. It uses standard word-boundary detection, counting any sequence of non-whitespace characters as a word.' },
      { q: 'Does it work with special characters?', a: 'Yes, it handles Unicode, emojis, and special characters correctly.' },
      { q: 'What is reading time based on?', a: 'Reading time is calculated at 200 words per minute, the average adult reading speed.' },
    ],
  },
  {
    id: 'text-case-converter',
    name: 'Text Case Converter',
    category: 'text',
    color: 'purple',
    icon: '🔡',
    shortDesc: 'Convert text to uppercase, lowercase, title case, camelCase & more.',
    longDesc: 'Instantly convert any text between multiple case formats: UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, and kebab-case. Essential for developers, writers, and content creators.',
    keywords: ['text case converter', 'uppercase converter', 'camelcase converter', 'snake case', 'title case tool'],
    relatedTools: ['slug-generator', 'word-counter', 'text-reverser'],
    faqs: [
      { q: 'What is camelCase?', a: 'camelCase writes compound words without spaces, capitalizing each word except the first: helloWorldExample.' },
      { q: 'What is the difference between PascalCase and camelCase?', a: 'PascalCase capitalizes the first letter too (HelloWorld), while camelCase starts lowercase (helloWorld).' },
    ],
  },
  {
    id: 'slug-generator',
    name: 'Slug Generator',
    category: 'text',
    color: 'coral',
    icon: '🔗',
    shortDesc: 'Generate clean, SEO-friendly URL slugs from any text.',
    longDesc: 'Generate SEO-friendly URL slugs from titles, headings, or any text. Automatically removes special characters, converts spaces to hyphens, and handles Unicode for clean, readable URLs.',
    keywords: ['slug generator', 'url slug', 'permalink generator', 'seo url', 'url friendly string'],
    relatedTools: ['url-slug-generator', 'meta-tag-generator', 'text-case-converter'],
    faqs: [
      { q: 'What is a URL slug?', a: 'A slug is the part of a URL that identifies a specific page in a readable, SEO-friendly way. E.g. /blog/my-awesome-post.' },
      { q: 'Should slugs be lowercase?', a: 'Yes. Lowercase slugs are standard for SEO and avoid duplicate content issues on case-sensitive servers.' },
    ],
  },
  {
    id: 'text-reverser',
    name: 'Text Reverser',
    category: 'text',
    color: 'pink',
    icon: '🔄',
    shortDesc: 'Reverse text, words, or lines in one click.',
    longDesc: 'Reverse any text character by character, word by word, or line by line. Useful for creative writing, puzzles, encoding tricks, and testing text-processing logic.',
    keywords: ['text reverser', 'reverse string', 'reverse words', 'reverse lines', 'backwards text'],
    relatedTools: ['text-case-converter', 'line-break-remover', 'text-sorter'],
    faqs: [
      { q: 'Can I reverse only words, not characters?', a: 'Yes. Choose "Reverse Words" to flip word order while keeping each word intact.' },
    ],
  },
  {
    id: 'remove-extra-spaces',
    name: 'Remove Extra Spaces',
    category: 'text',
    color: 'amber',
    icon: '✂️',
    shortDesc: 'Clean up whitespace and extra spaces from text instantly.',
    longDesc: 'Remove extra spaces, double spaces, leading/trailing whitespace, and non-breaking spaces from any text. Perfect for cleaning copied content, code, or raw data.',
    keywords: ['remove extra spaces', 'trim whitespace', 'clean text', 'remove double spaces', 'whitespace cleaner'],
    relatedTools: ['line-break-remover', 'duplicate-line-remover', 'word-counter'],
    faqs: [
      { q: 'Does this remove all spaces?', a: 'No. It collapses multiple consecutive spaces into one and removes leading/trailing spaces, preserving single spaces between words.' },
    ],
  },
  {
    id: 'duplicate-line-remover',
    name: 'Duplicate Line Remover',
    category: 'text',
    color: 'emerald',
    icon: '🗑️',
    shortDesc: 'Remove duplicate lines from any text block instantly.',
    longDesc: 'Instantly remove duplicate lines from any block of text. Options include case-sensitive matching, trimming whitespace before comparison, and preserving original order or sorting.',
    keywords: ['remove duplicate lines', 'deduplicate text', 'unique lines', 'remove duplicates', 'text deduplicator'],
    relatedTools: ['text-sorter', 'remove-extra-spaces', 'line-break-remover'],
    faqs: [
      { q: 'Is the comparison case-sensitive?', a: 'You can choose. With case-insensitive mode, "Hello" and "hello" are treated as duplicates.' },
    ],
  },
  {
    id: 'text-compare',
    name: 'Text Compare',
    category: 'text',
    color: 'teal',
    icon: '🔍',
    shortDesc: 'Compare two texts side by side and highlight differences.',
    longDesc: 'Compare two pieces of text and instantly see what is different. Highlights added, removed, and changed lines with color coding. Useful for reviewing edits, comparing versions, or spotting typos.',
    keywords: ['text compare', 'diff tool', 'text diff', 'compare texts', 'find differences in text'],
    relatedTools: ['duplicate-line-remover', 'text-sorter', 'word-counter'],
    faqs: [
      { q: 'Does it compare word by word or line by line?', a: 'Both. It shows line-level differences and optionally highlights changed words within each line.' },
    ],
  },
  {
    id: 'text-sorter',
    name: 'Text Sorter',
    category: 'text',
    color: 'purple',
    icon: '🔢',
    shortDesc: 'Sort lines alphabetically, reverse, numerically, or by length.',
    longDesc: 'Sort lines of text alphabetically (A–Z or Z–A), by line length, or numerically. Supports case-insensitive sorting and removing blank lines.',
    keywords: ['text sorter', 'sort lines', 'alphabetical sort', 'sort text online', 'line sorter'],
    relatedTools: ['duplicate-line-remover', 'text-compare', 'remove-extra-spaces'],
    faqs: [
      { q: 'Can I sort numbers?', a: 'Yes, numeric sort mode correctly orders 2, 10, 100 (not 10, 100, 2 like alphabetical).' },
    ],
  },
  {
    id: 'random-text-generator',
    name: 'Lorem Ipsum Generator',
    category: 'text',
    color: 'coral',
    icon: '🎲',
    shortDesc: 'Generate Lorem Ipsum and random placeholder text instantly.',
    longDesc: 'Generate Lorem Ipsum placeholder text for mockups, designs, and templates. Choose the number of words, sentences, or paragraphs. Also supports custom word-set generation.',
    keywords: ['lorem ipsum generator', 'placeholder text', 'dummy text', 'filler text', 'random text generator'],
    relatedTools: ['word-counter', 'text-case-converter', 'word-frequency-counter'],
    faqs: [
      { q: 'What is Lorem Ipsum?', a: 'Lorem Ipsum is scrambled Latin text used as placeholder content in design and publishing since the 1500s.' },
    ],
  },
  {
    id: 'line-break-remover',
    name: 'Line Break Remover',
    category: 'text',
    color: 'pink',
    icon: '↩️',
    shortDesc: 'Remove line breaks and newlines from any text.',
    longDesc: 'Remove all line breaks, carriage returns, and newlines from text. Options to join with a space, comma, or custom separator. Perfect for cleaning emails, PDF copies, and raw data.',
    keywords: ['remove line breaks', 'remove newlines', 'join lines', 'strip line breaks', 'single line text'],
    relatedTools: ['remove-extra-spaces', 'duplicate-line-remover', 'word-counter'],
    faqs: [
      { q: 'What is the difference between \\n and \\r\\n?', a: '\\n is Unix-style, \\r\\n is Windows-style. This tool handles both.' },
    ],
  },

  // ── DEVELOPER TOOLS ─────────────────────────────────────────
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    category: 'developer',
    color: 'teal',
    icon: '📋',
    shortDesc: 'Format, validate, and beautify JSON data with syntax checking.',
    longDesc: 'A powerful JSON formatter and validator that beautifies minified JSON, validates syntax, highlights errors with line numbers, and supports minification. Essential for developers working with APIs and data.',
    keywords: ['json formatter', 'json validator', 'json beautifier', 'format json online', 'json pretty print'],
    relatedTools: ['xml-formatter', 'csv-to-json', 'json-to-csv'],
    faqs: [
      { q: 'Can it detect JSON errors?', a: 'Yes. It pinpoints the exact line and character where the JSON syntax error occurred.' },
      { q: 'What indentation does it use?', a: '2 spaces by default. You can also choose 4 spaces or tab indentation.' },
    ],
  },
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder / Decoder',
    category: 'developer',
    color: 'purple',
    icon: '🔐',
    shortDesc: 'Encode & decode Base64 strings instantly in your browser.',
    longDesc: 'Encode any text or binary data to Base64 and decode Base64 back to readable text. Supports UTF-8, URL-safe Base64, and file-to-Base64 conversion.',
    keywords: ['base64 encoder', 'base64 decoder', 'encode base64', 'decode base64', 'base64 online'],
    relatedTools: ['url-encoder', 'image-to-base64', 'base64-to-image'],
    faqs: [
      { q: 'What is Base64?', a: 'Base64 is an encoding scheme that converts binary data to ASCII text using 64 safe characters.' },
      { q: 'Is URL-safe Base64 different?', a: 'Yes. URL-safe Base64 uses - and _ instead of + and / to avoid special meaning in URLs.' },
    ],
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder / Decoder',
    category: 'developer',
    color: 'coral',
    icon: '🌐',
    shortDesc: 'Encode & decode URL components and query strings.',
    longDesc: 'Properly encode URL components by converting special characters to percent-encoded sequences, and decode encoded URLs back to readable text. Supports both component and full URL encoding.',
    keywords: ['url encoder', 'url decoder', 'percent encoding', 'encode url online', 'uri encoder'],
    relatedTools: ['base64-encoder', 'slug-generator', 'meta-tag-generator'],
    faqs: [
      { q: 'What is the difference between encodeURI and encodeURIComponent?', a: 'encodeURI encodes a full URL (preserving :, /, ?, &). encodeURIComponent encodes a URL segment (encoding everything except unreserved chars).' },
    ],
  },
  {
    id: 'html-formatter',
    name: 'HTML Formatter / Beautifier',
    category: 'developer',
    color: 'pink',
    icon: '🖥️',
    shortDesc: 'Beautify and indent HTML code with configurable options.',
    longDesc: 'Automatically indent and format messy HTML code for readability. Supports custom indent size, attribute formatting, and self-closing tags. Great for reviewing templates or minified HTML.',
    keywords: ['html formatter', 'html beautifier', 'format html', 'html pretty print', 'html indenter'],
    relatedTools: ['css-minifier', 'js-minifier', 'xml-formatter'],
    faqs: [
      { q: 'Will it break my HTML?', a: 'No. The formatter only changes whitespace and indentation, not the structure or content of your HTML.' },
    ],
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    category: 'developer',
    color: 'amber',
    icon: '🎨',
    shortDesc: 'Minify CSS to reduce file size for faster loading.',
    longDesc: 'Compress CSS files by removing comments, whitespace, and redundant code without changing functionality. Shows original vs minified size and compression percentage.',
    keywords: ['css minifier', 'compress css', 'css optimizer', 'minify css online', 'css compressor'],
    relatedTools: ['js-minifier', 'html-formatter', 'css-gradient-generator'],
    faqs: [
      { q: 'Is minified CSS still valid?', a: 'Yes. Minification only removes non-essential characters. Browsers parse minified CSS exactly the same way.' },
    ],
  },
  {
    id: 'js-minifier',
    name: 'JavaScript Minifier',
    category: 'developer',
    color: 'emerald',
    icon: '⚡',
    shortDesc: 'Minify JavaScript code for faster production deployments.',
    longDesc: 'Compress JavaScript by removing comments, whitespace, and shortening variable names. Reduces file size significantly to improve page load speed and reduce bandwidth.',
    keywords: ['js minifier', 'javascript minifier', 'compress javascript', 'minify js online', 'js compressor'],
    relatedTools: ['css-minifier', 'html-formatter', 'base64-encoder'],
    faqs: [
      { q: 'Will minification break my JavaScript?', a: 'Simple minification (removing whitespace/comments) never breaks JS. Variable shortening can occasionally cause issues with eval or dynamic code.' },
    ],
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    category: 'developer',
    color: 'teal',
    icon: '🗄️',
    shortDesc: 'Format and beautify SQL queries for readability.',
    longDesc: 'Format messy SQL queries with proper indentation, keyword capitalization, and line breaks. Supports MySQL, PostgreSQL, SQLite, and SQL Server dialects.',
    keywords: ['sql formatter', 'sql beautifier', 'format sql', 'sql pretty print', 'sql query formatter'],
    relatedTools: ['json-formatter', 'xml-formatter', 'csv-to-json'],
    faqs: [
      { q: 'Which SQL dialects are supported?', a: 'MySQL, PostgreSQL, SQLite, and Microsoft SQL Server. Most standard SQL syntax is compatible across all.' },
    ],
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    category: 'developer',
    color: 'purple',
    icon: '📄',
    shortDesc: 'Format and validate XML documents with error detection.',
    longDesc: 'Beautify XML with proper indentation and line breaks. Validates well-formedness and reports syntax errors with line numbers. Useful for config files, RSS feeds, and SOAP responses.',
    keywords: ['xml formatter', 'xml beautifier', 'format xml online', 'xml validator', 'xml pretty print'],
    relatedTools: ['json-formatter', 'html-formatter', 'sitemap-generator'],
    faqs: [
      { q: 'Does it validate XML schema (XSD)?', a: 'It validates well-formedness (structure and syntax). Full XSD schema validation requires a server-side tool.' },
    ],
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Token Decoder',
    category: 'developer',
    color: 'coral',
    icon: '🎫',
    shortDesc: 'Decode and inspect JWT tokens without verification.',
    longDesc: 'Decode JWT (JSON Web Tokens) to inspect the header, payload, and signature. Parses claims like exp, iat, and sub. Useful for debugging authentication issues.',
    keywords: ['jwt decoder', 'jwt inspector', 'decode jwt', 'json web token decoder', 'jwt parser'],
    relatedTools: ['base64-encoder', 'json-formatter', 'encrypt-decrypt'],
    faqs: [
      { q: 'Is it safe to paste my JWT here?', a: 'This tool runs entirely in your browser. Your token is never sent to any server. That said, avoid pasting production tokens in public environments.' },
      { q: 'Can it verify the signature?', a: 'No. Verification requires the secret key or public certificate, which should never leave your server.' },
    ],
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    category: 'developer',
    color: 'pink',
    icon: '🔎',
    shortDesc: 'Test regular expressions with live match highlighting.',
    longDesc: 'Write and test regular expressions with real-time match highlighting, group extraction, and flag support (g, i, m, s). Shows all matches and captured groups.',
    keywords: ['regex tester', 'regular expression tester', 'regex online', 'test regex', 'regex validator'],
    relatedTools: ['json-formatter', 'text-compare', 'word-frequency-counter'],
    faqs: [
      { q: 'Which regex flavour is used?', a: 'JavaScript\'s built-in RegExp engine, which follows ECMAScript regex syntax.' },
      { q: 'What flags are supported?', a: 'g (global), i (case-insensitive), m (multiline), s (dotAll), and u (unicode).' },
    ],
  },

  // ── SECURITY TOOLS ──────────────────────────────────────────
  {
    id: 'password-generator',
    name: 'Password Generator',
    category: 'security',
    color: 'teal',
    icon: '🔑',
    shortDesc: 'Generate strong, secure passwords with custom rules.',
    longDesc: 'Generate cryptographically random passwords with full control over length, character sets (uppercase, lowercase, numbers, symbols), and count. All generation is done in-browser.',
    keywords: ['password generator', 'secure password', 'random password', 'strong password generator', 'online password maker'],
    relatedTools: ['password-strength-checker', 'uuid-generator', 'encrypt-decrypt'],
    faqs: [
      { q: 'Are generated passwords truly random?', a: 'Yes. We use crypto.getRandomValues(), the browser\'s cryptographically secure random number generator.' },
      { q: 'Are my passwords saved?', a: 'Never. Everything happens in your browser. We have no server-side logging.' },
    ],
  },
  {
    id: 'password-strength-checker',
    name: 'Password Strength Checker',
    category: 'security',
    color: 'purple',
    icon: '🛡️',
    shortDesc: 'Check password strength with a detailed security score and feedback.',
    longDesc: 'Analyze password strength against multiple criteria: length, complexity, character variety, common patterns, and dictionary words. Provides actionable feedback and an entropy score.',
    keywords: ['password strength checker', 'password security', 'password analyzer', 'check password strength', 'password meter'],
    relatedTools: ['password-generator', 'encrypt-decrypt', 'md5-generator'],
    faqs: [
      { q: 'What makes a password strong?', a: 'Length (12+ chars), a mix of uppercase/lowercase/numbers/symbols, no dictionary words, and no predictable patterns.' },
    ],
  },
  {
    id: 'md5-generator',
    name: 'MD5 Hash Generator',
    category: 'security',
    color: 'coral',
    icon: '#️⃣',
    shortDesc: 'Generate MD5 hash from any string instantly.',
    longDesc: 'Compute the MD5 hash of any text string. Displays the hash in hex, Base64, and uppercase formats. Note: MD5 is not secure for cryptographic use — use SHA-256 for security-critical applications.',
    keywords: ['md5 generator', 'md5 hash', 'generate md5', 'md5 online', 'md5 checksum'],
    relatedTools: ['sha256-generator', 'password-generator', 'base64-encoder'],
    faqs: [
      { q: 'Is MD5 secure?', a: 'MD5 is not cryptographically secure. It\'s vulnerable to collision attacks. Use SHA-256 or SHA-3 for security purposes.' },
      { q: 'Can I reverse an MD5 hash?', a: 'MD5 is a one-way function. You cannot mathematically reverse it, though common hashes may appear in rainbow tables.' },
    ],
  },
  {
    id: 'sha256-generator',
    name: 'SHA-256 Hash Generator',
    category: 'security',
    color: 'pink',
    icon: '🔒',
    shortDesc: 'Generate SHA-256 cryptographic hash from any text.',
    longDesc: 'Compute SHA-256 hashes in your browser using the Web Crypto API. Outputs in hex, Base64, and uppercase. SHA-256 is the industry-standard hash for security applications.',
    keywords: ['sha256 generator', 'sha256 hash', 'generate sha256', 'sha-256 online', 'crypto hash'],
    relatedTools: ['md5-generator', 'password-generator', 'base64-encoder'],
    faqs: [
      { q: 'Why SHA-256 over MD5?', a: 'SHA-256 is collision-resistant and computationally infeasible to reverse, making it safe for passwords, certificates, and data integrity.' },
    ],
  },
  {
    id: 'uuid-generator',
    name: 'UUID / GUID Generator',
    category: 'security',
    color: 'amber',
    icon: '🎯',
    shortDesc: 'Generate random UUID v4 / GUID values in multiple formats.',
    longDesc: 'Generate one or multiple RFC-compliant UUID v4 values. Output in standard, uppercase, no-hyphens, or braces format. Useful for database IDs, session tokens, and unique identifiers.',
    keywords: ['uuid generator', 'guid generator', 'generate uuid', 'random uuid', 'uuid v4'],
    relatedTools: ['password-generator', 'md5-generator', 'encrypt-decrypt'],
    faqs: [
      { q: 'What is the chance of UUID collision?', a: 'Essentially zero. With 2^122 possible UUIDs, the probability of collision is astronomically small.' },
      { q: 'What is UUID v4?', a: 'UUID v4 is randomly generated. It\'s the most common version used as database primary keys and unique identifiers.' },
    ],
  },
  {
    id: 'encrypt-decrypt',
    name: 'Text Encrypt / Decrypt',
    category: 'security',
    color: 'emerald',
    icon: '🔏',
    shortDesc: 'Encrypt and decrypt text with a passphrase using AES-256.',
    longDesc: 'Encrypt and decrypt messages using AES-256-GCM symmetric encryption with PBKDF2 key derivation. All processing is client-side. Never send sensitive data to a server.',
    keywords: ['text encrypt decrypt', 'aes encryption', 'encrypt text online', 'symmetric encryption', 'message encryption'],
    relatedTools: ['password-generator', 'base64-encoder', 'sha256-generator'],
    faqs: [
      { q: 'Is this encryption secure?', a: 'Yes. It uses AES-256-GCM with PBKDF2 key derivation — industry-standard symmetric encryption.' },
      { q: 'What if I lose the passphrase?', a: 'The encrypted message cannot be recovered without the correct passphrase. There is no backdoor.' },
    ],
  },

  // ── CONVERTERS ──────────────────────────────────────────────
  {
    id: 'csv-to-json',
    name: 'CSV to JSON Converter',
    category: 'converters',
    color: 'teal',
    icon: '📊',
    shortDesc: 'Convert CSV data to formatted JSON instantly.',
    longDesc: 'Paste CSV content and instantly convert it to a JSON array of objects. Supports custom delimiters, header row detection, and nested structure options.',
    keywords: ['csv to json', 'convert csv to json', 'csv json converter', 'csv parser', 'csv converter online'],
    relatedTools: ['json-to-csv', 'json-formatter', 'excel-to-json'],
    faqs: [
      { q: 'Does the first row become keys?', a: 'Yes by default. The first row is treated as column headers and becomes the keys in each JSON object.' },
      { q: 'Are custom delimiters supported?', a: 'Yes. Comma, semicolon, tab, and pipe are all supported.' },
    ],
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV Converter',
    category: 'converters',
    color: 'purple',
    icon: '📈',
    shortDesc: 'Convert JSON arrays to CSV spreadsheet format.',
    longDesc: 'Convert JSON arrays of objects to CSV format. Automatically detects all unique keys across objects and generates the appropriate CSV header row.',
    keywords: ['json to csv', 'convert json to csv', 'json csv converter', 'export json to csv', 'json to spreadsheet'],
    relatedTools: ['csv-to-json', 'json-formatter', 'excel-to-json'],
    faqs: [
      { q: 'What JSON structure is expected?', a: 'An array of objects, e.g. [{"name":"Alice","age":30},{"name":"Bob","age":25}].' },
    ],
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    category: 'converters',
    color: 'coral',
    icon: '📐',
    shortDesc: 'Convert length, weight, temperature, speed, and area units.',
    longDesc: 'Comprehensive unit converter supporting length (m, km, miles, feet), weight (kg, lbs, oz), temperature (°C, °F, K), speed (km/h, mph, m/s), and area units.',
    keywords: ['unit converter', 'length converter', 'weight converter', 'temperature converter', 'metric imperial converter'],
    relatedTools: ['number-base-converter', 'timezone-converter', 'percentage-calculator'],
    faqs: [
      { q: 'How accurate are the conversions?', a: 'Conversions use standard internationally-recognised conversion factors with up to 10 decimal places of precision.' },
    ],
  },
  {
    id: 'timezone-converter',
    name: 'Timezone Converter',
    category: 'converters',
    color: 'pink',
    icon: '🕐',
    shortDesc: 'Convert time between world timezones accurately.',
    longDesc: 'Convert date and time between any world timezone. Supports all IANA timezones and automatically accounts for DST (daylight saving time). Great for scheduling international meetings.',
    keywords: ['timezone converter', 'time zone converter', 'world time converter', 'convert time zones', 'dst timezone tool'],
    relatedTools: ['unit-converter', 'number-base-converter', 'word-counter'],
    faqs: [
      { q: 'Does it handle daylight saving time?', a: 'Yes. It uses the browser\'s built-in IANA timezone database which includes all DST transitions.' },
    ],
  },
  {
    id: 'number-base-converter',
    name: 'Number Base Converter',
    category: 'converters',
    color: 'amber',
    icon: '🔢',
    shortDesc: 'Convert between binary, octal, decimal, and hexadecimal.',
    longDesc: 'Convert numbers between any numeral base: binary (base 2), octal (base 8), decimal (base 10), hexadecimal (base 16), and any custom base from 2 to 36.',
    keywords: ['number base converter', 'binary converter', 'hex converter', 'octal converter', 'decimal to binary'],
    relatedTools: ['hex-to-rgb', 'unit-converter', 'json-formatter'],
    faqs: [
      { q: 'What is a number base?', a: 'A number base (or radix) defines how many unique digits a numeral system has. Base-10 has 0–9, Base-2 has 0–1, Base-16 has 0–9 plus A–F.' },
    ],
  },
  {
    id: 'excel-to-json',
    name: 'Excel / CSV to JSON',
    category: 'converters',
    color: 'emerald',
    icon: '📑',
    shortDesc: 'Convert spreadsheet data to structured JSON format.',
    longDesc: 'Paste spreadsheet data or CSV and convert it to JSON. Supports multiple sheets, nested objects, and array generation from tabular data.',
    keywords: ['excel to json', 'spreadsheet to json', 'csv to json converter', 'xlsx to json', 'convert excel to json'],
    relatedTools: ['csv-to-json', 'json-to-csv', 'json-formatter'],
    faqs: [
      { q: 'Can I upload an actual Excel file?', a: 'Currently, paste CSV/TSV data from Excel. Direct .xlsx file upload is coming in the next release.' },
    ],
  },

  // ── SEO TOOLS ───────────────────────────────────────────────
  {
    id: 'keyword-density-checker',
    name: 'Keyword Density Checker',
    category: 'seo',
    color: 'teal',
    icon: '📊',
    shortDesc: 'Analyze keyword density and frequency in your content.',
    longDesc: 'Calculate keyword density percentage, count occurrences, and identify the most frequent words in your content. Shows a density table and highlights over-optimised terms.',
    keywords: ['keyword density checker', 'keyword frequency', 'seo keyword density', 'keyword analysis', 'content keyword tool'],
    relatedTools: ['word-frequency-counter', 'word-counter', 'meta-tag-generator'],
    faqs: [
      { q: 'What is ideal keyword density?', a: '1%–3% is generally considered natural. Anything over 5% may be flagged as keyword stuffing by Google.' },
    ],
  },
  {
    id: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    category: 'seo',
    color: 'purple',
    icon: '🏷️',
    shortDesc: 'Generate complete HTML meta tags for SEO and social sharing.',
    longDesc: 'Generate all essential meta tags: title, description, robots, viewport, Open Graph (Facebook/LinkedIn), and Twitter Card. Preview how your page will appear in search and social feeds.',
    keywords: ['meta tag generator', 'seo meta tags', 'meta description generator', 'open graph generator', 'twitter card generator'],
    relatedTools: ['open-graph-generator', 'robots-txt-generator', 'keyword-density-checker'],
    faqs: [
      { q: 'What is the ideal meta description length?', a: '150–160 characters. Google truncates descriptions longer than ~160 chars in search results.' },
    ],
  },
  {
    id: 'robots-txt-generator',
    name: 'Robots.txt Generator',
    category: 'seo',
    color: 'coral',
    icon: '🤖',
    shortDesc: 'Create a robots.txt file to control search engine crawling.',
    longDesc: 'Generate a robots.txt file with rules for specific user agents (Googlebot, Bingbot, all bots). Set allowed/disallowed paths, crawl delay, and sitemap location.',
    keywords: ['robots txt generator', 'create robots txt', 'seo robots', 'disallow crawling', 'googlebot rules'],
    relatedTools: ['sitemap-generator', 'meta-tag-generator', 'open-graph-generator'],
    faqs: [
      { q: 'Does robots.txt prevent indexing?', a: 'Disallowing a URL in robots.txt prevents crawling but not necessarily indexing if other sites link to it. Use noindex meta tags to prevent indexing.' },
    ],
  },
  {
    id: 'sitemap-generator',
    name: 'XML Sitemap Generator',
    category: 'seo',
    color: 'pink',
    icon: '🗺️',
    shortDesc: 'Generate an XML sitemap for your website.',
    longDesc: 'Generate a standards-compliant XML sitemap. Enter your URLs with optional priority, change frequency, and last modified date. Download ready-to-upload XML.',
    keywords: ['sitemap generator', 'xml sitemap', 'create sitemap', 'sitemap xml generator', 'google sitemap'],
    relatedTools: ['robots-txt-generator', 'meta-tag-generator', 'open-graph-generator'],
    faqs: [
      { q: 'How do I submit a sitemap to Google?', a: 'Upload sitemap.xml to your root directory, then submit the URL in Google Search Console > Sitemaps.' },
    ],
  },
  {
    id: 'open-graph-generator',
    name: 'Open Graph Tag Generator',
    category: 'seo',
    color: 'amber',
    icon: '📱',
    shortDesc: 'Generate Open Graph meta tags for better social media sharing.',
    longDesc: 'Generate og:title, og:description, og:image, og:url, and Twitter Card meta tags. Preview how your link will appear when shared on Facebook, Twitter/X, LinkedIn, and WhatsApp.',
    keywords: ['open graph generator', 'og tags', 'social media meta tags', 'facebook meta tags', 'twitter card generator'],
    relatedTools: ['meta-tag-generator', 'sitemap-generator', 'robots-txt-generator'],
    faqs: [
      { q: 'What size should og:image be?', a: '1200×630 pixels (1.91:1 ratio) for Facebook and Twitter. At least 600×315 px minimum.' },
    ],
  },
  {
    id: 'url-slug-generator',
    name: 'URL Slug Generator',
    category: 'seo',
    color: 'emerald',
    icon: '🔗',
    shortDesc: 'Create SEO-friendly URL slugs from titles or any text.',
    longDesc: 'Generate clean, SEO-optimised URL slugs from blog titles, product names, or any text. Handles special characters, diacritics, and multiple languages.',
    keywords: ['url slug generator', 'seo url slug', 'url friendly string', 'permalink generator', 'slug maker'],
    relatedTools: ['slug-generator', 'meta-tag-generator', 'keyword-density-checker'],
    faqs: [
      { q: 'Should I include stop words in slugs?', a: 'Generally remove stop words (the, a, is, of) for shorter, keyword-focused URLs. E.g. "best-json-formatter" not "the-best-json-formatter".' },
    ],
  },
  {
    id: 'word-frequency-counter',
    name: 'Word Frequency Counter',
    category: 'seo',
    color: 'teal',
    icon: '📉',
    shortDesc: 'Count and rank word frequency in any content.',
    longDesc: 'Analyse word frequency across your content and see the most common words ranked by count. Exclude stop words, set minimum word length, and export results.',
    keywords: ['word frequency counter', 'word frequency analysis', 'most common words', 'text frequency', 'word occurrence counter'],
    relatedTools: ['keyword-density-checker', 'word-counter', 'text-compare'],
    faqs: [
      { q: 'What are stop words?', a: 'Stop words are common words (the, and, is, in) that carry little meaning. Excluding them gives a cleaner view of your content\'s actual keywords.' },
    ],
  },

  // ── UTILITY / IMAGE ─────────────────────────────────────────
  {
    id: 'image-to-base64',
    name: 'Image to Base64 Converter',
    category: 'utility',
    color: 'teal',
    icon: '🖼️',
    shortDesc: 'Convert images to Base64 encoded data URI strings.',
    longDesc: 'Upload any image (PNG, JPG, GIF, SVG, WebP) and convert it to a Base64 data URI. Use directly in HTML, CSS, or embed in JSON without external file references.',
    keywords: ['image to base64', 'convert image base64', 'base64 image encoder', 'data uri image', 'embed image base64'],
    relatedTools: ['base64-to-image', 'base64-encoder', 'hex-to-rgb'],
    faqs: [
      { q: 'When should I use Base64 images?', a: 'For small images (icons, logos) in CSS or HTML to save HTTP requests. Avoid for large images — they increase file size by ~33%.' },
    ],
  },
  {
    id: 'base64-to-image',
    name: 'Base64 to Image Converter',
    category: 'utility',
    color: 'purple',
    icon: '🎨',
    shortDesc: 'Decode Base64 data URIs back to viewable images.',
    longDesc: 'Paste a Base64-encoded image string and instantly preview the image. Download it in the original format. Supports all Base64 image data URIs.',
    keywords: ['base64 to image', 'decode base64 image', 'base64 image viewer', 'data uri to image', 'base64 image decoder'],
    relatedTools: ['image-to-base64', 'base64-encoder', 'hex-to-rgb'],
    faqs: [
      { q: 'What formats are supported?', a: 'Any image format that the browser supports: JPEG, PNG, GIF, WebP, SVG, BMP, and ICO.' },
    ],
  },
  {
    id: 'hex-to-rgb',
    name: 'Hex to RGB Converter',
    category: 'utility',
    color: 'coral',
    icon: '🎨',
    shortDesc: 'Convert hex color codes to RGB, HSL, and CSS values.',
    longDesc: 'Convert hexadecimal color codes to RGB, HSL, and CSS color values. Includes a color picker, live preview swatch, and support for 3-digit and 8-digit hex (with alpha).',
    keywords: ['hex to rgb', 'hex color converter', 'rgb to hex', 'color converter', 'hex color code'],
    relatedTools: ['css-gradient-generator', 'number-base-converter', 'image-to-base64'],
    faqs: [
      { q: 'What is the difference between RGB and HSL?', a: 'RGB defines colors by Red, Green, Blue channels (0–255). HSL defines by Hue (0–360°), Saturation, and Lightness — more intuitive for designers.' },
    ],
  },
  {
    id: 'css-gradient-generator',
    name: 'CSS Gradient Generator',
    category: 'utility',
    color: 'pink',
    icon: '🌈',
    shortDesc: 'Visually create CSS linear, radial, and conic gradients.',
    longDesc: 'Build beautiful CSS gradients with a live visual editor. Supports linear, radial, and conic gradient types. Add multiple color stops, adjust angle, and copy the ready-to-use CSS.',
    keywords: ['css gradient generator', 'gradient maker', 'linear gradient css', 'radial gradient tool', 'css background generator'],
    relatedTools: ['hex-to-rgb', 'css-minifier', 'html-formatter'],
    faqs: [
      { q: 'What is a CSS gradient?', a: 'A CSS gradient creates smooth transitions between two or more colors without needing an image file.' },
    ],
  },

  // ── BONUS TOOLS (to reach 50) ────────────────────────────────
  {
    id: 'markdown-to-html',
    name: 'Markdown to HTML',
    category: 'developer',
    color: 'amber',
    icon: '✍️',
    shortDesc: 'Convert Markdown to clean HTML with live preview.',
    longDesc: 'Convert Markdown text to HTML with a live side-by-side preview. Supports all CommonMark syntax: headings, bold, italic, links, images, code blocks, tables, and lists.',
    keywords: ['markdown to html', 'markdown converter', 'md to html', 'markdown parser', 'convert markdown'],
    relatedTools: ['html-formatter', 'text-case-converter', 'word-counter'],
    faqs: [
      { q: 'What Markdown flavour is supported?', a: 'CommonMark plus GitHub Flavored Markdown (GFM) extensions: tables, task lists, and strikethrough.' },
    ],
  },
  {
    id: 'json-to-xml',
    name: 'JSON to XML Converter',
    category: 'developer',
    color: 'emerald',
    icon: '🔀',
    shortDesc: 'Convert JSON data to well-formed XML documents.',
    longDesc: 'Transform JSON objects and arrays into valid, formatted XML. Customize the root element name, attribute handling, and indentation.',
    keywords: ['json to xml', 'convert json to xml', 'json xml converter', 'transform json xml', 'data format converter'],
    relatedTools: ['xml-formatter', 'json-formatter', 'csv-to-json'],
    faqs: [
      { q: 'How are JSON arrays converted to XML?', a: 'JSON arrays become repeated XML elements with the same tag name. The key is used as the element name.' },
    ],
  },
  {
    id: 'yaml-to-json',
    name: 'YAML to JSON Converter',
    category: 'developer',
    color: 'teal',
    icon: '⚙️',
    shortDesc: 'Convert YAML configuration files to JSON format.',
    longDesc: 'Parse and convert YAML to JSON and vice versa. Useful for working with Kubernetes configs, GitHub Actions, Docker Compose, and other YAML-heavy tools.',
    keywords: ['yaml to json', 'convert yaml json', 'yaml parser', 'json to yaml', 'yaml converter online'],
    relatedTools: ['json-formatter', 'xml-formatter', 'json-to-xml'],
    faqs: [
      { q: 'Are YAML comments preserved?', a: 'No. YAML comments are stripped during conversion as JSON does not support comments.' },
    ],
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    category: 'utility',
    color: 'amber',
    icon: '📊',
    shortDesc: 'Calculate percentages, increases, decreases, and margins.',
    longDesc: 'All-in-one percentage calculator: find X% of Y, what % is X of Y, percentage increase/decrease, reverse percentage, and profit margin calculations.',
    keywords: ['percentage calculator', 'percent calculator', 'percentage increase calculator', 'percent of number', 'calculate percentage online'],
    relatedTools: ['unit-converter', 'number-base-converter', 'word-frequency-counter'],
    faqs: [
      { q: 'How do I calculate percentage increase?', a: '((New Value − Old Value) / Old Value) × 100. E.g. from 80 to 100: ((100−80)/80)×100 = 25% increase.' },
    ],
  },
  {
    id: 'roman-numeral-converter',
    name: 'Roman Numeral Converter',
    category: 'converters',
    color: 'coral',
    icon: 'Ⅷ',
    shortDesc: 'Convert between Arabic numbers and Roman numerals.',
    longDesc: 'Convert numbers from 1 to 3,999 to Roman numerals and vice versa. Supports extended notation for larger numbers.',
    keywords: ['roman numeral converter', 'roman to arabic', 'arabic to roman', 'roman numeral calculator', 'convert roman numerals'],
    relatedTools: ['number-base-converter', 'unit-converter', 'percentage-calculator'],
    faqs: [
      { q: 'What is the largest standard Roman numeral?', a: 'MMMCMXCIX (3,999). Larger numbers require non-standard overbar notation.' },
    ],
  },
  {
    id: 'character-counter',
    name: 'Character Counter',
    category: 'text',
    color: 'emerald',
    icon: '🔡',
    shortDesc: 'Count characters with and without spaces, for Twitter, SMS & more.',
    longDesc: 'Count characters for Twitter (280), SMS (160), meta descriptions (160), and other platforms. Shows character limits with visual indicators.',
    keywords: ['character counter', 'char count', 'twitter character counter', 'sms character limit', 'text length counter'],
    relatedTools: ['word-counter', 'meta-tag-generator', 'text-case-converter'],
    faqs: [
      { q: 'Does Twitter count emoji as 1 or 2 characters?', a: 'Twitter counts most emoji and URLs as 2 characters due to t.co URL shortening and Unicode handling.' },
    ],
  },
  {
    id: 'color-palette-generator',
    name: 'Color Palette Generator',
    category: 'utility',
    color: 'purple',
    icon: '🎭',
    shortDesc: 'Generate beautiful color palettes and export as CSS variables.',
    longDesc: 'Create harmonious color palettes from a base color using color theory: complementary, analogous, triadic, and monochromatic schemes. Export as CSS variables, Tailwind config, or hex list.',
    keywords: ['color palette generator', 'color scheme generator', 'color palette maker', 'css color palette', 'design color palette'],
    relatedTools: ['hex-to-rgb', 'css-gradient-generator', 'css-minifier'],
    faqs: [
      { q: 'What is a complementary color scheme?', a: 'Complementary colors are opposite each other on the color wheel, creating high contrast. E.g. orange and teal.' },
    ],
  },
  {
    id: 'countdown-timer',
    name: 'Online Countdown Timer',
    category: 'utility',
    color: 'teal',
    icon: '⏱️',
    shortDesc: 'Set a countdown timer for any duration with alarm.',
    longDesc: 'Set a countdown for hours, minutes, and seconds. Plays an alarm when time is up, supports multiple timers, and saves timers to localStorage.',
    keywords: ['countdown timer', 'online timer', 'countdown clock', 'timer with alarm', 'free online countdown'],
    relatedTools: ['timezone-converter', 'word-counter', 'percentage-calculator'],
    faqs: [
      { q: 'Does the timer work when the tab is in the background?', a: 'Yes, using the Page Visibility API to keep time accurate even when the tab is not in focus.' },
    ],
  },
]

export function getToolById(id: string): Tool | undefined {
  return TOOLS.find(t => t.id === id)
}

export function getToolsByCategory(cat: ToolCategory): Tool[] {
  return TOOLS.filter(t => t.category === cat)
}

export function getRelatedTools(tool: Tool): Tool[] {
  return tool.relatedTools
    .map(id => TOOLS.find(t => t.id === id))
    .filter(Boolean) as Tool[]
}

export const CATEGORIES: { id: ToolCategory; name: string; icon: string; color: ColorKey; desc: string }[] = [
  { id: 'text',       name: 'Text Tools',      icon: '✏️',  color: 'teal',    desc: '12 tools for writing, editing & text manipulation' },
  { id: 'developer',  name: 'Developer Tools',  icon: '💻',  color: 'coral',   desc: '13 tools for JSON, code formatting & encoding' },
  { id: 'security',   name: 'Security Tools',   icon: '🔐',  color: 'pink',    desc: '6 tools for passwords, hashes & encryption' },
  { id: 'converters', name: 'Converters',       icon: '🔄',  color: 'amber',   desc: '8 tools to convert formats, units & bases' },
  { id: 'seo',        name: 'SEO Tools',        icon: '📈',  color: 'emerald', desc: '7 tools for meta tags, sitemaps & keywords' },
  { id: 'utility',    name: 'Utility Tools',    icon: '🎨',  color: 'purple',  desc: '7 tools for colors, gradients & calculations' },
]
